# -*- coding: utf-8 -*-
"""Casos Prácticos de Implementación-CDD2 grupo 2-Sede Villa Ojo De Agua.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XRRXQ_N0EstaK7feFSo3tsiXroO1Ccn
"""

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Cargar dataset
digits = load_digits()

X = digits.data
y = digits.target

print("Dimensiones del dataset:", X.shape)

# Dividir 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Crear modelo
modelo = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000)

# Entrenar
modelo.fit(X_train, y_train)

# Predecir
y_pred = modelo.predict(X_test)

# Precisión
print("Precisión:", accuracy_score(y_test, y_pred))

"""La red neuronal logró una alta precisión en la clasificación de dígitos, demostrando ser eficiente para problemas de reconocimiento de patrones."""

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

digits = load_digits()

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

modelo = RandomForestClassifier(
    n_estimators=100,
    criterion='entropy',
    max_depth=10
)

modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Precisión:", accuracy_score(y_test, y_pred))

"""Se observó que modificar los parámetros del bosque aleatorio impacta directamente en la precisión del modelo. La configuración óptima depende del dataset utilizado.
Por Ej. cambiando el max_depth entre 5,10 y 15 la mayor precision la da 10,liegp cambiando el criterion entre "gini" y "entropy" la mayor precision la da entropy.
"""

#Incluimos las librerías necesarias

import matplotlib.pyplot as plt

import numpy as np

from sklearn.tree import DecisionTreeRegressor



# Creamos un dataset aleatorio

rng = np.random.RandomState(1)

X = np.sort(5 * rng.rand(80, 1), axis=0)

y = np.cos(X).ravel()

y[::5] += 3 * (0.5 - rng.rand(16))



# Entrenamiento del modelo y definición de parámetros

regr_1 = DecisionTreeRegressor(max_depth=10)

regr_1.fit(X, y)



# Predicción

X_test = np.arange(0.0, 5.0, 0.01)[:, np.newaxis]

y_1 = regr_1.predict(X_test)



# Gráfico de entradas y salidas

plt.figure()

plt.scatter(X, y, s=20, edgecolor="black", c="darkorange", label="datos")

plt.plot(X_test, y_1, color="cornflowerblue", label="max_prof=2", linewidth=2)

plt.xlabel("datos")

plt.ylabel("objetivo")

plt.title("Regresión con Árbol de Decisión")

plt.legend()

plt.show()

"""En este ejercicio se observó que el parámetro max_depth influye directamente en el comportamiento del árbol de decisión. usando un max depth bajo como 2 nos da la curva "original" por decirle asi,y aunque la subamos por 3,5 o 7 valores la diferencia en la curva no se hace notable,solo se diferencia un cambio con un valor grande y lejano al valor original como 10 por ejemplo. Cuando se utilizan valores bajos, el modelo genera una curva simple que no logra ajustarse correctamente a los datos. Al aumentar la profundidad, el ajuste mejora, aunque valores excesivamente altos pueden producir sobreajuste.

Además, al reemplazar la función seno por coseno, se observó un cambio en la forma de la curva generada, demostrando que el modelo adapta su predicción según los datos de entrada.

Cordial saludo.

Sede Villa Ojo De Agua - Grupo 2
Integrantes:
Federico Claramunt
Javier Molina
Marcia Lovaiza
Soledad Rios
Francis Feijoo
"""

